# Generated by Django 6.0 on 2025-12-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_product2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product3w',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='todo.category')),
            ],
        ),
    ]
